### ISSUE TITLE
2015 Data Download Issue

### ISSUE THREAD

**Issue by Rahib4** [yash12392/tradewithpython-blogs#2]
I get error while downloading 2015 data.. It says "File is not a zip file". I believe you can also add some conditions to get rid of this issue.
I am using pretty much the same code that you had provided in your blog.

```
from random import randint
import time
from jugaad_data.nse import full_bhavcopy_save

date_range = pd.bdate_range(start='02/01/2015', end = '12/28/2015', 
                    freq='C', holidays = holidays(2015))

dates_2020 = [x.date() for x in date_range]

error_dates = []
for dates in dates_2020:
    year = dates.year
    print(year,'- ',dates)
    try:
        bhavcopy_save(dates, """to_path\\{0}\\""".format(year))
        # full_bhavcopy_save(dates, """to_path\\{0}\\""".format(year))
        time.sleep(randint(1,4)) #adding random delay of 1-4 seconds
    except Exception as e:
        print('Error - ',e)
        print('Error - 10 sec gap')
        time.sleep(10) #stop program for 10 seconds and try again.
        error_dates.append(dates)
        print(error_dates)
```

**Comment by yash12392** [comment]
The problem is not with the code, the problem is that data is not available in the archives on NSE website, in the background, the code calls the link in this format

"**https://archives.nseindia.com/content/historical/EQUITIES/{yyyy}/{MMM}/cm{dd}{MMM}{yyyy}bhav.csv.zip**"

Taking a recent example, for 9th December 2020, the link will be 

https://www1.nseindia.com/content/historical/EQUITIES/2020/DEC/cm09DEC2020bhav.csv.zip

For 2015 it would be, as 9th Dec 2015 was a trading day

https://www1.nseindia.com/content/historical/EQUITIES/2015/DEC/cm09DEC2015bhav.csv.zip

When you open the 2020 link in a browser, the file gets downloaded automatically, when you try and open the 2015 link, you will get an access denied error which means NSE is not allowing the files to be downloaded for that date/date range.

Hope that makes sense! If you need very old data, you will be better off paying a vendor for corporate action adjusted data.
